# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4e33bec2b5c6faa4fb18f1c7488b069a8ae0de3869e22f28570da8a372101fdb338a459122e61353c63faf62b692e5865b97774abed2193b010c4ec3c00868bd

test:
  secret_key_base: 76e4e6a7d3c645a00d64174ac75192caaf5b8c628a151cf3692737e3e04749e79a075de13d4c98a19e192eb51287f6e0a7ae997593c2d50e36c2818ccf1b36ee

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
